#!/bin/bash

# Get directory of the script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
INSTALLERSDIR=$DIR/installers
INSTALLERS=$(find $INSTALLERSDIR/* -type f | sed "s|$INSTALLERSDIR/||") # Regex uses | so we can use paths without escaping them

while getopts 'qv' opt
do
    case $opt in
        q)
            quiet=1
            shift;;
        v)
            verbose=1
            echo 'Printing verbosely!'
            shift;;
    esac
done

# Prompt user for selection if none were passed
if [[ -z $1 ]]; then
    echo "Install which files?"
    for file in  $INSTALLERS ; do
        echo ' *' $file
    done
    echo -n "Install: "
    read input
    choices=$input
else
    choices=$@
fi

if [[ $choices == 'all' ]]; then
    choices=$INSTALLERS
fi

# Run installers, if they exist, in the directory of this script
pushd $DIR > /dev/null
for choice in $choices ; do
    installer=$INSTALLERSDIR/$choice
    if [[ -x $installer ]]; then
        if [[ ! $quiet ]]; then
            echo -n "Installing $choice... "
        fi
        if [[ $verbose ]]; then
            echo ""
            $installer
        else
            $installer > /dev/null
        fi
    else
        echo "Failed to install \"$choice\""
    fi
    if [[ ! $quiet ]]; then
        echo "done."
    fi
done
popd > /dev/null
