#!/bin/bash
ln -sfv ${PWD}/.vim ~
ln -sfv ${PWD}/.vimrc ~
if [[ -d ~/.vim/bundle/Vundle.vim ]]; then
    echo "Vundle already installed"
else
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
fi
