#!/bin/bash
ln -sfv ${PWD}/.vim ~
ln -sfv ${PWD}/.vimrc ~

if [[ -d ~/.vim/autoload/Vundle.vim ]]; then
    echo "Plug already installed"
else
    echo "Cloning Plug"
    curl -so ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

echo "Installing Vim plugins..."
vim +PlugInstall +qall 2>&1
